#INCLUDE "TOTVS.ch"
#INCLUDE "PROTHEUS.ch"
#Include "FWMVCDef.ch"

//----------------------------------------------------------------------------------------------------------------------
/* {Protheus.doc} RELAT01
TELA
@author    BRUNO NASCIMENTO GONÇALVES
@since     17/10/2023
@version   12/superior
*/
//----------------------------------------------------------------------------------------------------------------------

USER FUNCTION MA440COR()
    Local aLegenda   := {}

    AADD(aLegenda, {"", "BR_VERMELHO","ATIVO"})

Return aLegenda
